// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Int = require("rescript/lib/js/belt_Int.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

function read_from_file(filename) {
  return Fs.readFileSync(filename, "utf8").split("\n");
}

var lines = Fs.readFileSync("input.txt", "utf8").split("\n");

var numbers = Belt_Array.map(Belt_Array.map(lines, Belt_Int.fromString), Belt_Option.getExn);

var numbers1 = Belt_Array.sliceToEnd(numbers, 1);

var numbers2 = Belt_Array.slice(numbers, 0, numbers.length - 1 | 0);

var count = Belt_Array.keep(Belt_Array.zip(numbers1, numbers2), (function (param) {
        return (param[0] - param[1] | 0) > 0;
      })).length;

console.log(count);

exports.read_from_file = read_from_file;
exports.lines = lines;
exports.numbers = numbers;
exports.numbers1 = numbers1;
exports.numbers2 = numbers2;
exports.count = count;
/* lines Not a pure module */
